name: Deploy Blog

on:
  push:
    branches:
      - master # 代码提交的时候触发构建部署
  schedule:
    - cron: "0 14 * * *"  # 定时任务：每天下午14点钟触发

env:
  TZ: Asia/Shanghai

jobs:
  build: # 一项叫做build的任务

    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    
    steps:
    - name: Checkout # 将仓库内master分支的内容下载到工作目录
      uses: actions/checkout@v1 # 脚本来自 https://github.com/actions/checkout
      
    - name: Use Node.js 10.x # 配置Node环境
      uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
      with:
        node-version: "10.x"
    
    - name: Setup Hexo env
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }} # 这里是上面WinterChenS.github.io新增的公钥：HEXO_DEPLOY_KEY
      run: |
        # set up private key for deploy
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        # set git infomation
        git config --global user.name 'winterchens' # 换成你自己的邮箱和名字
        git config --global user.email '1085143002@qq.com'
        # install dependencies
        npm i -g hexo-cli # 安装hexo
        npm i
        # 拉取主题代码
        rm -rf themes/*
        git clone https://github.com/winter-photograper/hexo-theme-magnetic.git themes/magnetic
        
  
    - name: Deploy
      run: |
        # publish
        hexo generate && hexo deploy # 执行部署程序    
        
    - name: Vercel Action
      # You may pin to the exact commit or the version.
      # uses: amondnet/vercel-action@77cb0ce3642a451f7f18d63821c0e26f7adead9a
      uses: amondnet/vercel-action@v19.0.1+3
      with:
        # Vercel token
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        # 
        # if you want to comment on pr and commit, set token
        github-token: ${{ secrets.OP_TOKEN }} # optional
        # if you want to create github deployment, set true, default: false
        github-deployment: false # optional, default is false
        # the working directory
        working-directory: ./ # optional
        # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
        vercel-project-id: ${{ secrets.PROJECT_ID}} # optional
        # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
        vercel-org-id: ${{ secrets.ORG_ID}} # optional
        vercel-args: '--prod'
